import os
import whisper
import soundfile as sf
import torch
import numpy as np
from qwen_tts import Qwen3TTSModel

# --- 1. CONFIGURATION ---
VOICE_NAME = "sandy"
SOURCES = {"spongebob": ["https://youtu.be/4nU1jXY_DU8", "00:00:50", "00:03:50"],
           "mrkrabs": ["https://youtu.be/rTK6mivE6N0", "00:00:10", "00:03:10"],
           "sandy": ["https://youtu.be/IyUKjvKhN6E", "00:00:10", "00:03:02"],
           "patrick": ["https://youtu.be/f68vJhc8ncg", "00:00:10", "00:03:00"],}
YOUTUBE_URL = SOURCES[VOICE_NAME][0]
REF_AUDIO = f"voices/{VOICE_NAME}/{VOICE_NAME}_source.wav"
REF_TEXT_FILE = f"voices/{VOICE_NAME}/{VOICE_NAME}_reference_text.txt"
START_TIME = SOURCES[VOICE_NAME][1]
END_TIME = SOURCES[VOICE_NAME][2]

MY_NEW_SCRIPT = "Barnacles! I can't believe I'm being generated by an artificial intelligence. Patrick, we're inside a computer!"

# --- 2. DOWNLOAD AUDIO FROM YOUTUBE ---
if not os.path.exists(REF_AUDIO):
    print("--- Downloading audio from YouTube... ---")
    # yt-dlp converts the video to a high-quality .wav
    command = (
        f'yt-dlp -x --audio-format wav '
        f'--download-sections "*{START_TIME}-{END_TIME}" '
        f'-o "voices/{VOICE_NAME}/{VOICE_NAME}_source.%(ext)s" {YOUTUBE_URL}'
    )
    os.system(command)
else:
    print("--- Source audio already exists. Skipping download. ---")

# --- 3. AUTO-TRANSCRIBE ---
if not os.path.exists(REF_TEXT_FILE):
    print("--- Whisper is transcribing... ---")
    whisper_model = whisper.load_model("base")
    result = whisper_model.transcribe(REF_AUDIO)
    reference_text = result['text'].strip()
    with open(REF_TEXT_FILE, 'w', encoding='utf-8') as f:
        f.write(reference_text)
else:
    with open(REF_TEXT_FILE, 'r', encoding='utf-8') as f:
        reference_text = f.read().strip()

print(f"--- Transcription Complete! Detected: {reference_text[:50]}...")

# --- Check if audio already generated for this text ---
generations_dir = f"generations/{VOICE_NAME}"
already_generated = False
if os.path.exists(generations_dir):
    for file in os.listdir(generations_dir):
        if file.endswith('.txt'):
            txt_path = os.path.join(generations_dir, file)
            with open(txt_path, 'r', encoding='utf-8') as f:
                if f.read().strip() == MY_NEW_SCRIPT:
                    already_generated = True
                    print(f"--- Audio already generated for this text. Skipping generation. ---")
                    break

if not already_generated:
    # --- 4. CLONE THE VOICE ---
    print("--- Initializing Qwen3-TTS (1.7B Model)... ---")
    model = Qwen3TTSModel.from_pretrained("Qwen/Qwen3-TTS-12Hz-1.7B-Base")

    print("--- Generating Cloned Speech... ---")
    # IMPORTANT: Qwen3-TTS usually returns a list of waveforms (wavs) and the sample rate (sr)
    wavs, sr = model.generate_voice_clone(
        ref_audio=REF_AUDIO,
        ref_text=reference_text,
        text=MY_NEW_SCRIPT,
        language="English"
    )

    # --- 5. FIXED SAVE RESULT ---
    # 1. Pick the first waveform from the list
    wav = wavs[0]

    # 2. Convert from Torch Tensor to Numpy
    if isinstance(wav, torch.Tensor):
        wav = wav.detach().cpu().numpy()

    # 3. Handle data shape and type (Soundfile expects float32/int16 and mono/stereo)
    wav = wav.squeeze() # Remove extra dimensions like (1, 44100) -> (44100,)
    if wav.dtype != np.float32:
        wav = wav.astype(np.float32)

else:
    # If already generated, skip to save, but since we don't have wav, perhaps just print
    print("--- Skipping save as audio already exists. ---")
    # But to avoid error, perhaps exit or something
    # Since the save is after, and we need wav, perhaps don't save again
    # But the user wants to check before creating, so if already created, don't create again
    # So, the save part should only run if not already_generated
    pass

# 4. Create generations folder if it doesn't exist (only if generating)
if not already_generated:
    os.makedirs(generations_dir, exist_ok=True)

    # 5. Find the next available number
    n = 1
    while os.path.exists(os.path.join(generations_dir, f"{n}.wav")) or os.path.exists(os.path.join(generations_dir, f"{n}.txt")):
        n += 1

    audio_file = os.path.join(generations_dir, f"{n}.wav")
    text_file = os.path.join(generations_dir, f"{n}.txt")

    # 6. Save audio
    try:
        sf.write(audio_file, wav, sr)
        print(f"--- SUCCESS! Audio saved as: {audio_file} ---")
    except Exception as e:
        print(f"--- Error saving audio: {e} ---")

    # 7. Save text
    try:
        with open(text_file, 'w', encoding='utf-8') as f:
            f.write(MY_NEW_SCRIPT)
        print(f"--- Text saved as: {text_file} ---")
    except Exception as e:
        print(f"--- Error saving text: {e} ---")